### ISSUE TITLE
onboarding

### ISSUE THREAD

**Issue by TomTasche** [TomTasche/OpenDocument.ios#13]
we do show a short introduction / tutorial when the user first opens the app on Android. we should do the same for iOS

**Comment by wdesimini** [comment]
@TomTasche I'm down to work on this. Do you have a screenshot of how the tutorial looks on Android? I could try to replicate it in the app, or if it's just a series of views showing instructions I can add in the photos/videos if you have them

**Comment by TomTasche** [comment]
I'd love to see you contribute @wdesimini!

Here are some screenshots:
![Screenshot_20190626-213029](https://user-images.githubusercontent.com/128734/60208175-b445ba00-9868-11e9-8202-15caa636cdab.png)
![Screenshot_20190626-213035](https://user-images.githubusercontent.com/128734/60208187-ba3b9b00-9868-11e9-84d6-728ebb1f85b5.png)
![Screenshot_20190626-213038](https://user-images.githubusercontent.com/128734/60208192-bd368b80-9868-11e9-8315-74e96c578206.png)

Here's the code in case that helps: https://github.com/TomTasche/OpenDocument.droid/blob/master/app/src/main/java/at/tomtasche/reader/ui/activity/IntroActivity.java#L25
Images: https://github.com/TomTasche/OpenDocument.droid/tree/master/app/src/main/res/drawable-xxxhdpi
Text: https://github.com/TomTasche/OpenDocument.droid/blob/master/app/src/main/res/values/strings.xml#L53-L59

I can also offer the raw .psd-files if you know how to work with that.
