### ISSUE TITLE
improve launch screen

### ISSUE THREAD

**Issue by TomTasche** [TomTasche/OpenDocument.ios#14]
easiest thing would be to just show the app icon on a grey-ish background? or we reuse the first page of the tutorial? see #13

**Comment by TomTasche** [comment]
what we show in one of our app store screenshots (on Android) looks good to me: https://lh3.googleusercontent.com/axgOpiGU1OrlWKiVpf7veIJ5yUxDSXEiHCdXKCd0Hb96DeGGetJEI3YVivMNhQuGLKX7=w3360-h1752-rw

**Comment by jeed2424** [comment]
I loved the "app logo" idea, but it's unfortunately forbidden by Apple, see: https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/launch-screen/

It's a pain in the ass to work with Apple's guidelines...

**Comment by TomTasche** [comment]
Oh wow I didn't know that! That's so weird... i thought apps like Facebook, etc would also show a launch screen that only consists of their logo.

**Comment by jeed2424** [comment]
Yeah, I had doubts too after writing this comment so I checked and apps like Instagram and Snapchat use "non-loaded" versions of their app before it actually loads: 
![IMG_2036](https://user-images.githubusercontent.com/50756835/58000432-bddc4500-7aa6-11e9-9595-3feeae175b96.PNG)

**Comment by TomTasche** [comment]
Well, if that's what Apple wants us to do... 🤷‍♂️ Sounds good to me.
